#undef TRACE_DEFINE_ENUM
#undef TRACE_DEFINE_SIZEOF
#undef TRACE_EVENT
#undef __field
#undef __field_ext
#undef __field_struct
#undef __field_struct_ext
#undef __array
#undef __dynamic_array
#undef __bitmask
#undef TP_STRUCT__entry
#undef DECLARE_EVENT_CLASS
#undef DEFINE_EVENT
#undef DEFINE_EVENT_FN
#undef DEFINE_EVENT_PRINT
#undef TRACE_EVENT_FN
#undef TRACE_EVENT_FN_COND
#undef TRACE_EVENT_FLAGS
#undef TRACE_EVENT_PERF_PERM
